const code = {
  binary: [
    "def find_threshold_date(series, target):",
    "    lo, hi = 0, len(series) - 1",
    "    result = None",
    "    while lo <= hi:",
    "        mid = (lo + hi) // 2",
    "        if series[mid].value >= target:",
    "            result = series[mid]",
    "            hi = mid - 1",
    "        else:",
    "            lo = mid + 1",
    "    return result",
  ],
  bfs: [
    "queue = deque([(start_url, 0)])",
    "seen.add(start_url)",
    "while queue:",
    "    url, depth = queue.popleft()",
    "    visit(url, depth)",
    "    if depth >= max_depth:",
    "        continue",
    "    for child in get_children(url):",
    "        if child not in seen:",
    "            seen.add(child)",
    "            queue.append((child, depth + 1))",
  ],
  dfs: [
    "stack = [root]",
    "while stack:",
    "    current = stack.pop()",
    "    if current.is_file() and match(current):",
    "        results.append(current)",
    "    elif current.is_dir() and current.name not in skip_dirs:",
    "        children = sorted(current.iterdir(), reverse=True)",
    "        stack.extend(children)",
    "return results",
  ],
  rabin: [
    "for pat_len, pat_group in patterns_by_length.items():",
    "    text_hash = hash(text[:pat_len])",
    "    for i in range(len(text) - pat_len + 1):",
    "        if i > 0:",
    "            text_hash = roll_hash(text_hash, i)",
    "        for pattern, pattern_hash in pat_group:",
    "            if text_hash == pattern_hash:",
    "                if text[i:i + pat_len] == pattern:",
    "                    findings.append((pattern, i))",
  ],
  heap: [
    "heap = []",
    "for record in campaign_stream:",
    "    entry = CampaignScore(record['roas'], record['id'])",
    "    if len(heap) < k:",
    "        heappush(heap, entry)",
    "    elif entry.score > heap[0].score:",
    "        heapreplace(heap, entry)",
    "return sorted(heap, reverse=True)",
  ],
  topo: [
    "queue = deque(tasks_with_no_dependencies)",
    "while queue:",
    "    wave = list(queue)",
    "    waves.append(wave)",
    "    queue.clear()",
    "    for task in wave:",
    "        for dependent in graph[task]:",
    "            in_degree[dependent] -= 1",
    "            if in_degree[dependent] == 0:",
    "                queue.append(dependent)",
  ],
  bloom: [
    "def might_contain(item):",
    "    return all(bit_array[i] for i in hash_indices(item))",
    "",
    "for url in urls:",
    "    if bloom.might_contain(url):",
    "        skip(url)",
    "    else:",
    "        process(url)",
    "        bloom.add(url)",
  ],
  buffer: [
    "def append(item):",
    "    buffer[head] = item",
    "    head = (head + 1) % capacity",
    "    count = min(count + 1, capacity)",
    "",
    "def latest(n):",
    "    walk backward from head",
    "    return most recent items",
  ],
  dijkstra: [
    "dist[start] = 0",
    "heap = [(0, start)]",
    "while heap:",
    "    cost, node = heappop(heap)",
    "    if node == end:",
    "        return reconstruct_path(prev)",
    "    for edge in graph[node]:",
    "        new_cost = cost + edge.cost",
    "        if new_cost < dist[edge.target]:",
    "            dist[edge.target] = new_cost",
    "            prev[edge.target] = node",
    "            heappush(heap, (new_cost, edge.target))",
  ],
  union: [
    "def find(x):",
    "    if parent[x] != x:",
    "        parent[x] = find(parent[x])",
    "    return parent[x]",
    "",
    "def union(x, y):",
    "    rx, ry = find(x), find(y)",
    "    if rx == ry: return",
    "    attach smaller rank tree to larger rank tree",
  ],
};

export const operations = [
  "All",
  "Find",
  "Explore",
  "Order",
  "Deduplicate",
  "Route",
  "Memory",
  "Security",
];

export const algorithms = [
  {
    id: "binary",
    title: "Binary Search",
    operation: "Find",
    short: "Campaign threshold finder",
    complexity: "O(log n)",
    summary:
      "Find the first day a sorted campaign metric crosses a target without scanning every row.",
    agentUse:
      "A skill or MCP endpoint can answer threshold questions over long time series without spending tokens or API time on a full scan.",
    code: code.binary,
    steps: [
      { line: 1, label: "Initial bounds", note: "The CPA series is sorted by date. We start with the full window and target 6.00.", lo: 0, hi: 6, mid: null, result: null },
      { line: 5, label: "Check middle", note: "The middle value is 5.80, still below the target, so the breach must be to the right.", lo: 0, hi: 6, mid: 3, result: null },
      { line: 10, label: "Move right", note: "Discard the earlier half. The search window now covers 2026-03-05 to 2026-03-07.", lo: 4, hi: 6, mid: null, result: null },
      { line: 5, label: "Check middle", note: "The middle value is 7.40, which crosses the target. Store it, then keep searching earlier.", lo: 4, hi: 6, mid: 5, result: 5 },
      { line: 8, label: "Tighten left", note: "Move the high pointer left to test whether the breach happened before 2026-03-06.", lo: 4, hi: 4, mid: null, result: 5 },
      { line: 5, label: "Earliest breach", note: "2026-03-05 is 6.25, also above target. It becomes the earliest known breach.", lo: 4, hi: 4, mid: 4, result: 4 },
      { line: 11, label: "Return", note: "The first threshold crossing is 2026-03-05.", lo: 4, hi: 3, mid: null, result: 4 },
    ],
  },
  {
    id: "bfs",
    title: "BFS",
    operation: "Explore",
    short: "Site crawler by depth",
    complexity: "O(V + E)",
    summary: "Audit landing pages level by level before descending into deeper archives.",
    agentUse:
      "A site-audit skill can prioritise high-traffic top-level pages before spending time on lower-value deep pages.",
    code: code.bfs,
    steps: [
      { line: 1, label: "Seed queue", note: "Start at the homepage with depth 0.", active: "/", queue: ["/"], visited: ["/"] },
      { line: 4, label: "Visit home", note: "Audit the home page, then enqueue its direct children.", active: "/", queue: ["/products", "/blog", "/about"], visited: ["/", "/products", "/blog", "/about"] },
      { line: 4, label: "Visit products", note: "The products page is audited before any blog post, because BFS stays on the current depth.", active: "/products", queue: ["/blog", "/about", "/products/shoes", "/products/hats"], visited: ["/", "/products", "/blog", "/about", "/products/shoes", "/products/hats"] },
      { line: 4, label: "Visit blog", note: "Blog children enter the queue after existing depth-one pages.", active: "/blog", queue: ["/about", "/products/shoes", "/products/hats", "/blog/post-1", "/blog/post-2"], visited: ["/", "/products", "/blog", "/about", "/products/shoes", "/products/hats", "/blog/post-1", "/blog/post-2"] },
      { line: 4, label: "Visit about", note: "Finish the level-one set before drilling deeper.", active: "/about", queue: ["/products/shoes", "/products/hats", "/blog/post-1", "/blog/post-2", "/about/team"], visited: ["/", "/products", "/blog", "/about", "/products/shoes", "/products/hats", "/blog/post-1", "/blog/post-2", "/about/team"] },
      { line: 11, label: "Continue breadth first", note: "The crawler now works through all depth-two pages.", active: "/products/shoes", queue: ["/products/hats", "/blog/post-1", "/blog/post-2", "/about/team"], visited: ["/", "/products", "/blog", "/about", "/products/shoes", "/products/hats", "/blog/post-1", "/blog/post-2", "/about/team"] },
    ],
  },
  {
    id: "dfs",
    title: "DFS",
    operation: "Explore",
    short: "Repository scanner",
    complexity: "O(V + E)",
    summary: "Follow one folder path to its end before backtracking to the next branch.",
    agentUse:
      "A maintenance skill can discover SKILL.md, AGENTS.md, and package files in nested repos without holding an entire level in memory.",
    code: code.dfs,
    steps: [
      { line: 1, label: "Seed stack", note: "The scanner starts with the repository root.", active: "repo", stack: ["repo"], found: [] },
      { line: 3, label: "Pop repo", note: "Push children in reverse order so the next pop follows the natural first branch.", active: "repo", stack: ["docs", "packages", "skills"], found: [] },
      { line: 3, label: "Enter skills", note: "Depth-first traversal follows the skills branch before checking packages.", active: "skills", stack: ["docs", "packages", "weekly-review"], found: [] },
      { line: 4, label: "Find SKILL.md", note: "A matching config file is collected.", active: "SKILL.md", stack: ["docs", "packages"], found: ["skills/weekly-review/SKILL.md"] },
      { line: 3, label: "Backtrack", note: "The scanner returns to packages after finishing the skills branch.", active: "packages", stack: ["docs", "mcp-server"], found: ["skills/weekly-review/SKILL.md"] },
      { line: 4, label: "Find package.json", note: "The MCP package file is collected.", active: "package.json", stack: ["docs"], found: ["skills/weekly-review/SKILL.md", "packages/mcp-server/package.json"] },
    ],
  },
  {
    id: "rabin",
    title: "Rabin-Karp",
    operation: "Security",
    short: "Multi-pattern scanner",
    complexity: "O(n + m)",
    summary: "Scan content against suspicious prompt-injection and compliance phrases with rolling hashes.",
    agentUse:
      "An MCP tool can check external page content before passing it to the model, then verify hash hits to avoid false positives.",
    code: code.rabin,
    steps: [
      { line: 1, label: "Group patterns", note: "Patterns are grouped by length so each rolling window has comparable hashes.", window: [0, 7], hits: [] },
      { line: 2, label: "Hash first window", note: "The first window is not suspicious, so the scanner rolls forward.", window: [8, 15], hits: [] },
      { line: 5, label: "Rolling scan", note: "The window advances across the landing page content.", window: [16, 33], hits: [] },
      { line: 7, label: "Hash match", note: "A hash matches a known prompt-injection phrase. The scanner verifies the actual text.", window: [34, 62], hits: [[34, 62]] },
      { line: 9, label: "Record finding", note: "The phrase is confirmed and added to the findings list.", window: [34, 62], hits: [[34, 62]] },
      { line: 7, label: "Compliance match", note: "A second phrase is detected later in the copy.", window: [86, 104], hits: [[34, 62], [86, 104]] },
    ],
  },
  {
    id: "heap",
    title: "Heap",
    operation: "Order",
    short: "Top-K campaign tracker",
    complexity: "O(n log k)",
    summary: "Keep the best campaigns as data streams in, without sorting the full dataset every time.",
    agentUse:
      "A reporting skill can maintain a live top-five ROAS leaderboard while ingesting platform data from several MCP tools.",
    code: code.heap,
    steps: [
      { line: 1, label: "Empty heap", note: "The min-heap keeps only the top three records in this demo.", heap: [], incoming: "Spring Search 4.2" },
      { line: 4, label: "Push", note: "Spring Search enters the heap.", heap: [["Spring Search", 4.2]], incoming: "Retargeting 6.1" },
      { line: 4, label: "Push", note: "Retargeting is added. The smallest top-K item remains easy to inspect.", heap: [["Spring Search", 4.2], ["Retargeting", 6.1]], incoming: "Display 1.8" },
      { line: 4, label: "Fill K", note: "Display fills the third slot, but it is now the minimum.", heap: [["Display", 1.8], ["Retargeting", 6.1], ["Spring Search", 4.2]], incoming: "Clearance 5.8" },
      { line: 6, label: "Replace minimum", note: "Clearance beats the current minimum, so Display is replaced.", heap: [["Spring Search", 4.2], ["Retargeting", 6.1], ["Clearance", 5.8]], incoming: "Loyalty Email 7.3" },
      { line: 6, label: "Replace again", note: "Loyalty Email beats Spring Search and enters the leaderboard.", heap: [["Clearance", 5.8], ["Retargeting", 6.1], ["Loyalty Email", 7.3]], incoming: "Done" },
    ],
  },
  {
    id: "topo",
    title: "Topological Sort",
    operation: "Route",
    short: "Pipeline scheduler",
    complexity: "O(V + E)",
    summary: "Resolve dependency order and identify which workflow steps can run in parallel.",
    agentUse:
      "An orchestrator can fan out independent fetches, wait at the join, and fail early if a circular dependency is declared.",
    code: code.topo,
    steps: [
      { line: 1, label: "Ready tasks", note: "Three fetch jobs have no dependencies and can run together.", wave: 0, done: [] },
      { line: 3, label: "Wave 1", note: "Fetch Google Ads, Meta Ads, and Analytics in parallel.", wave: 1, done: ["fetch_google_ads", "fetch_meta_ads", "fetch_analytics"] },
      { line: 8, label: "Unlock transform", note: "All inputs are ready, so transform_data reaches in-degree zero.", wave: 2, done: ["fetch_google_ads", "fetch_meta_ads", "fetch_analytics", "transform_data"] },
      { line: 8, label: "Unlock metrics", note: "Calculated metrics wait until transformed data exists.", wave: 3, done: ["fetch_google_ads", "fetch_meta_ads", "fetch_analytics", "transform_data", "calculate_metrics"] },
      { line: 8, label: "Unlock narrative", note: "The narrative model call runs only after deterministic metric calculation.", wave: 4, done: ["fetch_google_ads", "fetch_meta_ads", "fetch_analytics", "transform_data", "calculate_metrics", "generate_narrative"] },
      { line: 10, label: "Report ready", note: "Build and distribute the report after all prerequisites are satisfied.", wave: 5, done: ["fetch_google_ads", "fetch_meta_ads", "fetch_analytics", "transform_data", "calculate_metrics", "generate_narrative", "build_report", "distribute_report"] },
    ],
  },
  {
    id: "bloom",
    title: "Bloom Filter",
    operation: "Deduplicate",
    short: "URL duplicate gate",
    complexity: "O(k)",
    summary: "Use a small bit array to cheaply ask whether a URL was probably seen before.",
    agentUse:
      "A crawler avoids repeated API calls or model scans. A positive answer is probabilistic; a negative answer is definitive.",
    code: code.bloom,
    steps: [
      { line: 3, label: "First URL", note: "No bits are set for the shoes URL, so the crawler processes it.", bits: [2, 7, 11], active: [2, 7, 11], url: "products/shoes", seen: false },
      { line: 9, label: "Add bits", note: "Three hash positions are turned on for the shoes URL.", bits: [2, 7, 11], active: [2, 7, 11], url: "products/shoes", seen: false },
      { line: 3, label: "Second URL", note: "The blog URL maps to a different set of bits, so it is processed.", bits: [2, 4, 7, 11, 13], active: [4, 13, 7], url: "blog/post-1", seen: false },
      { line: 5, label: "Duplicate check", note: "The shoes URL maps to positions that are already on. The crawler can skip or confirm in storage.", bits: [2, 4, 7, 11, 13], active: [2, 7, 11], url: "products/shoes", seen: true },
      { line: 8, label: "New URL", note: "The hats URL has at least one off bit, so it has definitely not been seen.", bits: [2, 4, 6, 7, 11, 13, 14], active: [6, 14, 2], url: "products/hats", seen: false },
    ],
  },
  {
    id: "buffer",
    title: "Circular Buffer",
    operation: "Memory",
    short: "Recent activity window",
    complexity: "O(1)",
    summary: "Keep the last N tool calls or report runs in fixed memory by overwriting the oldest slot.",
    agentUse:
      "A plugin or long-running harness can retain recent context without growing an unbounded log.",
    code: code.buffer,
    steps: [
      { line: 1, label: "Append Mar 31", note: "The first report run lands at slot 0.", head: 1, items: ["03-31", null, null, null, null] },
      { line: 2, label: "Append Apr 01", note: "The head advances after every write.", head: 2, items: ["03-31", "04-01", null, null, null] },
      { line: 2, label: "Append Apr 02", note: "A failed run is still retained in the rolling window.", head: 3, items: ["03-31", "04-01", "04-02 fail", null, null] },
      { line: 2, label: "Fill buffer", note: "The fifth write fills the buffer.", head: 0, items: ["03-31", "04-01", "04-02 fail", "04-03", "04-04"] },
      { line: 3, label: "Overwrite oldest", note: "The next write wraps around and replaces Mar 31.", head: 1, items: ["04-05", "04-01", "04-02 fail", "04-03", "04-04"] },
      { line: 7, label: "Latest three", note: "Walking backward from the head returns Apr 05, Apr 04, and Apr 03.", head: 1, items: ["04-05", "04-01", "04-02 fail", "04-03", "04-04"], latest: [0, 4, 3] },
    ],
  },
  {
    id: "dijkstra",
    title: "Dijkstra",
    operation: "Route",
    short: "Cheapest tool path",
    complexity: "O((V + E) log V)",
    summary: "Choose the lowest-cost route through a weighted graph of tool calls, caches, and transforms.",
    agentUse:
      "An orchestrator can trade latency, rate limits, and token cost explicitly instead of choosing a tool path by habit.",
    code: code.dijkstra,
    steps: [
      { line: 1, label: "Start", note: "The agent needs report-ready data. The current cost at need_data is zero.", active: "need_data", settled: [], path: [] },
      { line: 8, label: "Explore data routes", note: "Direct API costs 50. Cached warehouse costs 120.", active: "need_data", settled: ["need_data"], path: ["raw_api_data"] },
      { line: 10, label: "Set transformed cost", note: "Raw API plus transform costs 80, better than warehouse plus transform at 130.", active: "raw_api_data", settled: ["need_data", "raw_api_data"], path: ["raw_api_data", "transformed"] },
      { line: 10, label: "Analyse", note: "The analysis step raises total path cost to 160.", active: "transformed", settled: ["need_data", "raw_api_data", "transformed"], path: ["raw_api_data", "transformed", "analysed"] },
      { line: 5, label: "End reached", note: "Formatting adds 20, giving a total cost of 180.", active: "report_ready", settled: ["need_data", "raw_api_data", "transformed", "analysed", "report_ready"], path: ["raw_api_data", "transformed", "analysed", "report_ready"] },
    ],
  },
  {
    id: "union",
    title: "Union-Find",
    operation: "Deduplicate",
    short: "Incident clustering",
    complexity: "Near O(1)",
    summary: "Merge campaigns that share a root cause and count distinct problem clusters.",
    agentUse:
      "A monitoring agent can group related failures so a team fixes one cause instead of triaging five noisy alerts.",
    code: code.union,
    steps: [
      { line: 1, label: "Initial sets", note: "Each campaign starts as its own cluster.", groups: [["Spring Search"], ["Brand Display"], ["Retargeting"], ["New Customer"], ["Clearance"], ["Holiday Video"]] },
      { line: 6, label: "Shared audience", note: "Spring Search and Brand Display share the 18-24 UK targeting segment.", groups: [["Spring Search", "Brand Display"], ["Retargeting"], ["New Customer"], ["Clearance"], ["Holiday Video"]] },
      { line: 6, label: "Merge third campaign", note: "Retargeting shares the same segment, so it joins the first root cause cluster.", groups: [["Spring Search", "Brand Display", "Retargeting"], ["New Customer"], ["Clearance"], ["Holiday Video"]] },
      { line: 6, label: "Broken landing page", note: "New Customer and Clearance share a broken landing page.", groups: [["Spring Search", "Brand Display", "Retargeting"], ["New Customer", "Clearance"], ["Holiday Video"]] },
      { line: 3, label: "Compressed result", note: "Six alerts reduce to three distinct root causes.", groups: [["Spring Search", "Brand Display", "Retargeting"], ["New Customer", "Clearance"], ["Holiday Video"]] },
    ],
  },
];
