const code = {
  binary: [
    "def find_threshold_date(series, target):",
    "    lo, hi = 0, len(series) - 1",
    "    result = None",
    "    while lo <= hi:",
    "        mid = (lo + hi) // 2",
    "        if series[mid].value >= target:",
    "            result = series[mid]",
    "            hi = mid - 1",
    "        else:",
    "            lo = mid + 1",
    "    return result",
  ],
  bfs: [
    "queue = deque([(start_url, 0)])",
    "seen.add(start_url)",
    "while queue:",
    "    url, depth = queue.popleft()",
    "    visit(url, depth)",
    "    if depth >= max_depth:",
    "        continue",
    "    for child in get_children(url):",
    "        if child not in seen:",
    "            seen.add(child)",
    "            queue.append((child, depth + 1))",
  ],
  dfs: [
    "stack = [root]",
    "while stack:",
    "    current = stack.pop()",
    "    if current.is_file() and match(current):",
    "        results.append(current)",
    "    elif current.is_dir() and current.name not in skip_dirs:",
    "        children = sorted(current.iterdir(), reverse=True)",
    "        stack.extend(children)",
    "return results",
  ],
  rabin: [
    "for pat_len, pat_group in patterns_by_length.items():",
    "    text_hash = hash(text[:pat_len])",
    "    for i in range(len(text) - pat_len + 1):",
    "        if i > 0:",
    "            text_hash = roll_hash(text_hash, i)",
    "        for pattern, pattern_hash in pat_group:",
    "            if text_hash == pattern_hash:",
    "                if text[i:i + pat_len] == pattern:",
    "                    findings.append((pattern, i))",
  ],
  heap: [
    "heap = []",
    "for record in campaign_stream:",
    "    entry = CampaignScore(record['roas'], record['id'])",
    "    if len(heap) < k:",
    "        heappush(heap, entry)",
    "    elif entry.score > heap[0].score:",
    "        heapreplace(heap, entry)",
    "return sorted(heap, reverse=True)",
  ],
  topo: [
    "queue = deque(tasks_with_no_dependencies)",
    "while queue:",
    "    wave = list(queue)",
    "    waves.append(wave)",
    "    queue.clear()",
    "    for task in wave:",
    "        for dependent in graph[task]:",
    "            in_degree[dependent] -= 1",
    "            if in_degree[dependent] == 0:",
    "                queue.append(dependent)",
  ],
  bloom: [
    "def might_contain(item):",
    "    return all(bit_array[i] for i in hash_indices(item))",
    "",
    "for url in urls:",
    "    if bloom.might_contain(url):",
    "        skip(url)",
    "    else:",
    "        process(url)",
    "        bloom.add(url)",
  ],
  buffer: [
    "def append(item):",
    "    buffer[head] = item",
    "    head = (head + 1) % capacity",
    "    count = min(count + 1, capacity)",
    "",
    "def latest(n):",
    "    walk backward from head",
    "    return most recent items",
  ],
  dijkstra: [
    "dist[start] = 0",
    "heap = [(0, start)]",
    "while heap:",
    "    cost, node = heappop(heap)",
    "    if node == end:",
    "        return reconstruct_path(prev)",
    "    for edge in graph[node]:",
    "        new_cost = cost + edge.cost",
    "        if new_cost < dist[edge.target]:",
    "            dist[edge.target] = new_cost",
    "            prev[edge.target] = node",
    "            heappush(heap, (new_cost, edge.target))",
  ],
  union: [
    "def find(x):",
    "    if parent[x] != x:",
    "        parent[x] = find(parent[x])",
    "    return parent[x]",
    "",
    "def union(x, y):",
    "    rx, ry = find(x), find(y)",
    "    if rx == ry: return",
    "    attach smaller rank tree to larger rank tree",
  ],
  approval: [
    "state = 'proposed'",
    "if policy.rejects(action):",
    "    state = 'rejected'",
    "elif action.requires_approval:",
    "    state = 'awaiting_approval'",
    "elif approver.accepts(action):",
    "    state = 'approved'",
    "state = 'executing'",
    "state = execute(action)",
  ],
  tokenBucket: [
    "tokens = min(capacity, tokens + elapsed * refill_rate)",
    "if tokens >= request_cost:",
    "    tokens -= request_cost",
    "    allow(tool_call)",
    "else:",
    "    delay_until_refill(tool_call)",
  ],
  leaseQueue: [
    "action = claim_next_approved_action(now)",
    "if action.lock_expires_at > now:",
    "    skip(action)",
    "action.lock_token = uuid()",
    "action.lock_expires_at = now + lease_seconds",
    "heartbeat(action.lock_token)",
    "execute(action)",
    "release_or_fail(action)",
  ],
  permissionGraph: [
    "principal = agent.identity",
    "roles = resolve_roles(principal)",
    "for rule in policy.rules:",
    "    if rule.matches(principal, resource, action, context):",
    "        decision = rule.effect",
    "        break",
    "return decision == 'allow'",
  ],
  hashChain: [
    "previous_hash = log.tail_hash",
    "event = canonical_json(action_record)",
    "event_hash = sha256(previous_hash + event)",
    "append({ event, previous_hash, event_hash })",
    "verify by replaying hashes from genesis",
  ],
};

const algorithmContext = {
  binary: {
    why: "Binary search exists because ordered data should not be scanned one row at a time. Once the data is sorted, each comparison can discard half of the remaining search space.",
    optimizes: "Fast lookup and boundary detection over sorted records.",
    stillUsed: "Database indexes, log search, time-series thresholds, autocomplete, feature flags, and range queries.",
    remember: "If the data is sorted and you need a target or crossing point, halve the search space instead of scanning.",
  },
  bfs: {
    why: "Breadth-first search was built for exploring graphs level by level. It is useful when the nearest or highest-priority layer matters before deeper detail.",
    optimizes: "Coverage by distance or hierarchy depth.",
    stillUsed: "Web crawlers, shortest-path discovery in unweighted graphs, account audits, dependency maps, and queue-based workflows.",
    remember: "Use BFS when breadth and priority by level matter more than following one path deeply.",
  },
  dfs: {
    why: "Depth-first search exists for walking a structure by following one branch until it ends, then backtracking. It keeps memory small on deep structures.",
    optimizes: "Deep traversal with a small active working set.",
    stillUsed: "Repository scans, parsers, tree processing, cycle detection, dependency tracing, and backtracking systems.",
    remember: "Use DFS when the useful answer may live deep inside one branch.",
  },
  rabin: {
    why: "Rabin-Karp was created to make text search faster by comparing hashes of text windows instead of repeatedly comparing full strings.",
    optimizes: "Multi-pattern matching across large text with cheap rolling updates.",
    stillUsed: "Plagiarism detection, malware signatures, document scanning, search indexing, compliance checks, and prompt-injection filters.",
    remember: "Use hashes to find likely matches quickly, then verify the actual text.",
  },
  heap: {
    why: "Heaps solve the problem of repeatedly needing the next best or next smallest item without sorting the whole dataset every time.",
    optimizes: "Priority access and streaming top-K selection.",
    stillUsed: "Schedulers, priority queues, leaderboards, stream processing, pathfinding, and background job systems.",
    remember: "Use a heap when you only need the best few items, not a fully sorted list.",
  },
  topo: {
    why: "Topological sort exists because some tasks can only run after their prerequisites. It turns a dependency graph into a safe execution order.",
    optimizes: "Dependency-aware scheduling and parallel execution waves.",
    stillUsed: "Build systems, workflow engines, package managers, data pipelines, and multi-agent orchestration.",
    remember: "If steps depend on other steps, schedule the graph before running the work.",
  },
  bloom: {
    why: "Bloom filters were designed to answer a practical question with very little memory: have we probably seen this item before?",
    optimizes: "Fast membership checks when exact storage would be too expensive.",
    stillUsed: "CDNs, databases, crawlers, caches, stream deduplication, and large-scale filtering systems.",
    remember: "A Bloom filter can say definitely not seen or probably seen, never definitely seen.",
  },
  buffer: {
    why: "Circular buffers exist to keep a fixed-size rolling window without growing memory forever. New entries overwrite the oldest entries.",
    optimizes: "Recent history with bounded memory and constant-time writes.",
    stillUsed: "Telemetry, logs, audio buffers, monitoring windows, tool-call history, and embedded systems.",
    remember: "Use a circular buffer when only the latest N items matter.",
  },
  dijkstra: {
    why: "Dijkstra's algorithm was created to find the cheapest path through a weighted network where each step has a different cost.",
    optimizes: "Lowest-cost routing when all edge costs are non-negative.",
    stillUsed: "Network routing, maps, service planning, compiler optimization, dependency paths, and tool-chain selection.",
    remember: "When every route has a cost, model the system as a graph and let the cheapest path win.",
  },
  union: {
    why: "Union-Find exists to track which items belong to the same group while groups keep merging over time.",
    optimizes: "Fast clustering and connectivity checks.",
    stillUsed: "Network connectivity, image segmentation, graph algorithms, incident grouping, deduplication, and community detection.",
    remember: "Use Union-Find when many small links need to become clear clusters.",
  },
  approval: {
    why: "State machines formalize workflows that must move through allowed states. They prevent vague approval logic from becoming ad hoc conditionals.",
    optimizes: "Predictable transitions, auditability, and blocked unsafe execution.",
    stillUsed: "Payments, publishing systems, campaign approvals, CI/CD gates, ticketing workflows, and compliance systems.",
    remember: "If an action has a lifecycle, make the states explicit.",
  },
  tokenBucket: {
    why: "Token buckets were created for traffic shaping: allow short bursts while enforcing a sustained rate limit over time.",
    optimizes: "Throughput control without banning reasonable bursts.",
    stillUsed: "API gateways, rate limiters, ad platform integrations, model budgets, queue control, and network traffic management.",
    remember: "Let work proceed only when the bucket has enough capacity tokens.",
  },
  leaseQueue: {
    why: "Lease-locked queues solve the problem of multiple workers trying to run the same job while still recovering if one worker crashes.",
    optimizes: "Single execution with crash recovery.",
    stillUsed: "Distributed job queues, workflow engines, background workers, media operations, and scheduled automation.",
    remember: "Claim work with an expiring lease so duplicate workers cannot execute it at the same time.",
  },
  permissionGraph: {
    why: "RBAC and ABAC systems were created to make access decisions explicit across users, roles, resources, actions, and context.",
    optimizes: "Fine-grained authorization before a tool or data source is touched.",
    stillUsed: "Cloud IAM, enterprise apps, data platforms, agent gateways, CRM controls, and regulated workflows.",
    remember: "Resolve identity, resource, action, and context before allowing a tool call.",
  },
  hashChain: {
    why: "Hash chains make tampering visible by linking each record to the hash of the record before it.",
    optimizes: "Integrity checks for ordered logs.",
    stillUsed: "Audit trails, ledgers, append-only logs, supply-chain records, deployment provenance, and security monitoring.",
    remember: "If changing one event breaks the following hash, silent edits become detectable.",
  },
};

export const operations = [
  "All",
  "Find",
  "Explore",
  "Order",
  "Deduplicate",
  "Route",
  "Memory",
  "Security",
  "Control",
];

const algorithmItems = [
  {
    id: "binary",
    title: "Binary Search",
    operation: "Find",
    short: "Campaign threshold finder",
    complexity: "O(log n)",
    summary:
      "Find the first day a sorted campaign metric crosses a target without scanning every row.",
    agentUse:
      "A skill or MCP endpoint can answer threshold questions over long time series without spending tokens or API time on a full scan.",
    code: code.binary,
    steps: [
      { line: 1, label: "Initial bounds", note: "The CPA series is sorted by date. We start with the full window and target 6.00.", lo: 0, hi: 6, mid: null, result: null },
      { line: 5, label: "Check middle", note: "The middle value is 5.80, still below the target, so the breach must be to the right.", lo: 0, hi: 6, mid: 3, result: null },
      { line: 10, label: "Move right", note: "Discard the earlier half. The search window now covers 2026-03-05 to 2026-03-07.", lo: 4, hi: 6, mid: null, result: null },
      { line: 5, label: "Check middle", note: "The middle value is 7.40, which crosses the target. Store it, then keep searching earlier.", lo: 4, hi: 6, mid: 5, result: 5 },
      { line: 8, label: "Tighten left", note: "Move the high pointer left to test whether the breach happened before 2026-03-06.", lo: 4, hi: 4, mid: null, result: 5 },
      { line: 5, label: "Earliest breach", note: "2026-03-05 is 6.25, also above target. It becomes the earliest known breach.", lo: 4, hi: 4, mid: 4, result: 4 },
      { line: 11, label: "Return", note: "The first threshold crossing is 2026-03-05.", lo: 4, hi: 3, mid: null, result: 4 },
    ],
  },
  {
    id: "bfs",
    title: "BFS",
    operation: "Explore",
    short: "Site crawler by depth",
    complexity: "O(V + E)",
    summary: "Audit landing pages level by level before descending into deeper archives.",
    agentUse:
      "A site-audit skill can prioritise high-traffic top-level pages before spending time on lower-value deep pages.",
    code: code.bfs,
    steps: [
      { line: 1, label: "Seed queue", note: "Start at the homepage with depth 0.", active: "/", queue: ["/"], visited: ["/"] },
      { line: 4, label: "Visit home", note: "Audit the home page, then enqueue its direct children.", active: "/", queue: ["/products", "/blog", "/about"], visited: ["/", "/products", "/blog", "/about"] },
      { line: 4, label: "Visit products", note: "The products page is audited before any blog post, because BFS stays on the current depth.", active: "/products", queue: ["/blog", "/about", "/products/shoes", "/products/hats"], visited: ["/", "/products", "/blog", "/about", "/products/shoes", "/products/hats"] },
      { line: 4, label: "Visit blog", note: "Blog children enter the queue after existing depth-one pages.", active: "/blog", queue: ["/about", "/products/shoes", "/products/hats", "/blog/post-1", "/blog/post-2"], visited: ["/", "/products", "/blog", "/about", "/products/shoes", "/products/hats", "/blog/post-1", "/blog/post-2"] },
      { line: 4, label: "Visit about", note: "Finish the level-one set before drilling deeper.", active: "/about", queue: ["/products/shoes", "/products/hats", "/blog/post-1", "/blog/post-2", "/about/team"], visited: ["/", "/products", "/blog", "/about", "/products/shoes", "/products/hats", "/blog/post-1", "/blog/post-2", "/about/team"] },
      { line: 11, label: "Continue breadth first", note: "The crawler now works through all depth-two pages.", active: "/products/shoes", queue: ["/products/hats", "/blog/post-1", "/blog/post-2", "/about/team"], visited: ["/", "/products", "/blog", "/about", "/products/shoes", "/products/hats", "/blog/post-1", "/blog/post-2", "/about/team"] },
    ],
  },
  {
    id: "dfs",
    title: "DFS",
    operation: "Explore",
    short: "Repository scanner",
    complexity: "O(V + E)",
    summary: "Follow one folder path to its end before backtracking to the next branch.",
    agentUse:
      "A maintenance skill can discover SKILL.md, AGENTS.md, and package files in nested repos without holding an entire level in memory.",
    code: code.dfs,
    steps: [
      { line: 1, label: "Seed stack", note: "The scanner starts with the repository root.", active: "repo", stack: ["repo"], found: [] },
      { line: 3, label: "Pop repo", note: "Push children in reverse order so the next pop follows the natural first branch.", active: "repo", stack: ["docs", "packages", "skills"], found: [] },
      { line: 3, label: "Enter skills", note: "Depth-first traversal follows the skills branch before checking packages.", active: "skills", stack: ["docs", "packages", "weekly-review"], found: [] },
      { line: 4, label: "Find SKILL.md", note: "A matching config file is collected.", active: "SKILL.md", stack: ["docs", "packages"], found: ["skills/weekly-review/SKILL.md"] },
      { line: 3, label: "Backtrack", note: "The scanner returns to packages after finishing the skills branch.", active: "packages", stack: ["docs", "mcp-server"], found: ["skills/weekly-review/SKILL.md"] },
      { line: 4, label: "Find package.json", note: "The MCP package file is collected.", active: "package.json", stack: ["docs"], found: ["skills/weekly-review/SKILL.md", "packages/mcp-server/package.json"] },
    ],
  },
  {
    id: "rabin",
    title: "Rabin-Karp",
    operation: "Security",
    short: "Multi-pattern scanner",
    complexity: "O(n + m)",
    summary: "Scan content against suspicious prompt-injection and compliance phrases with rolling hashes.",
    agentUse:
      "An MCP tool can check external page content before passing it to the model, then verify hash hits to avoid false positives.",
    code: code.rabin,
    steps: [
      { line: 1, label: "Group patterns", note: "Patterns are grouped by length so each rolling window has comparable hashes.", window: [0, 7], hits: [] },
      { line: 2, label: "Hash first window", note: "The first window is not suspicious, so the scanner rolls forward.", window: [8, 15], hits: [] },
      { line: 5, label: "Rolling scan", note: "The window advances across the landing page content.", window: [16, 33], hits: [] },
      { line: 7, label: "Hash match", note: "A hash matches a known prompt-injection phrase. The scanner verifies the actual text.", window: [34, 62], hits: [[34, 62]] },
      { line: 9, label: "Record finding", note: "The phrase is confirmed and added to the findings list.", window: [34, 62], hits: [[34, 62]] },
      { line: 7, label: "Compliance match", note: "A second phrase is detected later in the copy.", window: [86, 104], hits: [[34, 62], [86, 104]] },
    ],
  },
  {
    id: "heap",
    title: "Heap",
    operation: "Order",
    short: "Top-K campaign tracker",
    complexity: "O(n log k)",
    summary: "Keep the best campaigns as data streams in, without sorting the full dataset every time.",
    agentUse:
      "A reporting skill can maintain a live top-five ROAS leaderboard while ingesting platform data from several MCP tools.",
    code: code.heap,
    steps: [
      { line: 1, label: "Empty heap", note: "The min-heap keeps only the top three records in this demo.", heap: [], incoming: "Spring Search 4.2" },
      { line: 4, label: "Push", note: "Spring Search enters the heap.", heap: [["Spring Search", 4.2]], incoming: "Retargeting 6.1" },
      { line: 4, label: "Push", note: "Retargeting is added. The smallest top-K item remains easy to inspect.", heap: [["Spring Search", 4.2], ["Retargeting", 6.1]], incoming: "Display 1.8" },
      { line: 4, label: "Fill K", note: "Display fills the third slot, but it is now the minimum.", heap: [["Display", 1.8], ["Retargeting", 6.1], ["Spring Search", 4.2]], incoming: "Clearance 5.8" },
      { line: 6, label: "Replace minimum", note: "Clearance beats the current minimum, so Display is replaced.", heap: [["Spring Search", 4.2], ["Retargeting", 6.1], ["Clearance", 5.8]], incoming: "Loyalty Email 7.3" },
      { line: 6, label: "Replace again", note: "Loyalty Email beats Spring Search and enters the leaderboard.", heap: [["Clearance", 5.8], ["Retargeting", 6.1], ["Loyalty Email", 7.3]], incoming: "Done" },
    ],
  },
  {
    id: "topo",
    title: "Topological Sort",
    operation: "Route",
    short: "Pipeline scheduler",
    complexity: "O(V + E)",
    summary: "Resolve dependency order and identify which workflow steps can run in parallel.",
    agentUse:
      "An orchestrator can fan out independent fetches, wait at the join, and fail early if a circular dependency is declared.",
    code: code.topo,
    steps: [
      { line: 1, label: "Ready tasks", note: "Three fetch jobs have no dependencies and can run together.", wave: 0, done: [] },
      { line: 3, label: "Wave 1", note: "Fetch Google Ads, Meta Ads, and Analytics in parallel.", wave: 1, done: ["fetch_google_ads", "fetch_meta_ads", "fetch_analytics"] },
      { line: 8, label: "Unlock transform", note: "All inputs are ready, so transform_data reaches in-degree zero.", wave: 2, done: ["fetch_google_ads", "fetch_meta_ads", "fetch_analytics", "transform_data"] },
      { line: 8, label: "Unlock metrics", note: "Calculated metrics wait until transformed data exists.", wave: 3, done: ["fetch_google_ads", "fetch_meta_ads", "fetch_analytics", "transform_data", "calculate_metrics"] },
      { line: 8, label: "Unlock narrative", note: "The narrative model call runs only after deterministic metric calculation.", wave: 4, done: ["fetch_google_ads", "fetch_meta_ads", "fetch_analytics", "transform_data", "calculate_metrics", "generate_narrative"] },
      { line: 10, label: "Report ready", note: "Build and distribute the report after all prerequisites are satisfied.", wave: 5, done: ["fetch_google_ads", "fetch_meta_ads", "fetch_analytics", "transform_data", "calculate_metrics", "generate_narrative", "build_report", "distribute_report"] },
    ],
  },
  {
    id: "bloom",
    title: "Bloom Filter",
    operation: "Deduplicate",
    short: "URL duplicate gate",
    complexity: "O(k)",
    summary: "Use a small bit array to cheaply ask whether a URL was probably seen before.",
    agentUse:
      "A crawler avoids repeated API calls or model scans. A positive answer is probabilistic; a negative answer is definitive.",
    code: code.bloom,
    steps: [
      { line: 3, label: "First URL", note: "No bits are set for the shoes URL, so the crawler processes it.", bits: [2, 7, 11], active: [2, 7, 11], url: "products/shoes", seen: false },
      { line: 9, label: "Add bits", note: "Three hash positions are turned on for the shoes URL.", bits: [2, 7, 11], active: [2, 7, 11], url: "products/shoes", seen: false },
      { line: 3, label: "Second URL", note: "The blog URL maps to a different set of bits, so it is processed.", bits: [2, 4, 7, 11, 13], active: [4, 13, 7], url: "blog/post-1", seen: false },
      { line: 5, label: "Duplicate check", note: "The shoes URL maps to positions that are already on. The crawler can skip or confirm in storage.", bits: [2, 4, 7, 11, 13], active: [2, 7, 11], url: "products/shoes", seen: true },
      { line: 8, label: "New URL", note: "The hats URL has at least one off bit, so it has definitely not been seen.", bits: [2, 4, 6, 7, 11, 13, 14], active: [6, 14, 2], url: "products/hats", seen: false },
    ],
  },
  {
    id: "buffer",
    title: "Circular Buffer",
    operation: "Memory",
    short: "Recent activity window",
    complexity: "O(1)",
    summary: "Keep the last N tool calls or report runs in fixed memory by overwriting the oldest slot.",
    agentUse:
      "A plugin or long-running harness can retain recent context without growing an unbounded log.",
    code: code.buffer,
    steps: [
      { line: 1, label: "Append Mar 31", note: "The first report run lands at slot 0.", head: 1, items: ["03-31", null, null, null, null] },
      { line: 2, label: "Append Apr 01", note: "The head advances after every write.", head: 2, items: ["03-31", "04-01", null, null, null] },
      { line: 2, label: "Append Apr 02", note: "A failed run is still retained in the rolling window.", head: 3, items: ["03-31", "04-01", "04-02 fail", null, null] },
      { line: 2, label: "Fill buffer", note: "The fifth write fills the buffer.", head: 0, items: ["03-31", "04-01", "04-02 fail", "04-03", "04-04"] },
      { line: 3, label: "Overwrite oldest", note: "The next write wraps around and replaces Mar 31.", head: 1, items: ["04-05", "04-01", "04-02 fail", "04-03", "04-04"] },
      { line: 7, label: "Latest three", note: "Walking backward from the head returns Apr 05, Apr 04, and Apr 03.", head: 1, items: ["04-05", "04-01", "04-02 fail", "04-03", "04-04"], latest: [0, 4, 3] },
    ],
  },
  {
    id: "dijkstra",
    title: "Dijkstra",
    operation: "Route",
    short: "Cheapest tool path",
    complexity: "O((V + E) log V)",
    summary: "Choose the lowest-cost route through a weighted graph of tool calls, caches, and transforms.",
    agentUse:
      "An orchestrator can trade latency, rate limits, and token cost explicitly instead of choosing a tool path by habit.",
    code: code.dijkstra,
    steps: [
      { line: 1, label: "Start", note: "The agent needs report-ready data. The current cost at need_data is zero.", active: "need_data", settled: [], path: [] },
      { line: 8, label: "Explore data routes", note: "Direct API costs 50. Cached warehouse costs 120.", active: "need_data", settled: ["need_data"], path: ["raw_api_data"] },
      { line: 10, label: "Set transformed cost", note: "Raw API plus transform costs 80, better than warehouse plus transform at 130.", active: "raw_api_data", settled: ["need_data", "raw_api_data"], path: ["raw_api_data", "transformed"] },
      { line: 10, label: "Analyse", note: "The analysis step raises total path cost to 160.", active: "transformed", settled: ["need_data", "raw_api_data", "transformed"], path: ["raw_api_data", "transformed", "analysed"] },
      { line: 5, label: "End reached", note: "Formatting adds 20, giving a total cost of 180.", active: "report_ready", settled: ["need_data", "raw_api_data", "transformed", "analysed", "report_ready"], path: ["raw_api_data", "transformed", "analysed", "report_ready"] },
    ],
  },
  {
    id: "union",
    title: "Union-Find",
    operation: "Deduplicate",
    short: "Incident clustering",
    complexity: "Near O(1)",
    summary: "Merge campaigns that share a root cause and count distinct problem clusters.",
    agentUse:
      "A monitoring agent can group related failures so a team fixes one cause instead of triaging five noisy alerts.",
    code: code.union,
    steps: [
      { line: 1, label: "Initial sets", note: "Each campaign starts as its own cluster.", groups: [["Spring Search"], ["Brand Display"], ["Retargeting"], ["New Customer"], ["Clearance"], ["Holiday Video"]] },
      { line: 6, label: "Shared audience", note: "Spring Search and Brand Display share the 18-24 UK targeting segment.", groups: [["Spring Search", "Brand Display"], ["Retargeting"], ["New Customer"], ["Clearance"], ["Holiday Video"]] },
      { line: 6, label: "Merge third campaign", note: "Retargeting shares the same segment, so it joins the first root cause cluster.", groups: [["Spring Search", "Brand Display", "Retargeting"], ["New Customer"], ["Clearance"], ["Holiday Video"]] },
      { line: 6, label: "Broken landing page", note: "New Customer and Clearance share a broken landing page.", groups: [["Spring Search", "Brand Display", "Retargeting"], ["New Customer", "Clearance"], ["Holiday Video"]] },
      { line: 3, label: "Compressed result", note: "Six alerts reduce to three distinct root causes.", groups: [["Spring Search", "Brand Display", "Retargeting"], ["New Customer", "Clearance"], ["Holiday Video"]] },
    ],
  },
  {
    id: "approval",
    title: "Approval State Machine",
    operation: "Control",
    short: "Action lifecycle gate",
    complexity: "O(1) per transition",
    summary:
      "Move risky agent actions through explicit states so execution only happens after policy and approval checks.",
    agentUse:
      "A campaign agent can propose budget, bid, or publishing actions without being allowed to execute them until the harness records approval.",
    code: code.approval,
    steps: [
      { line: 1, label: "Proposed", note: "The agent proposes a budget increase, but the action starts as a record, not an execution.", active: "proposed", approved: ["proposed"], action: "increase_budget" },
      { line: 4, label: "Approval required", note: "Policy marks this as high risk because it changes spend.", active: "awaiting_approval", approved: ["proposed", "awaiting_approval"], action: "increase_budget" },
      { line: 6, label: "Human review", note: "The approver checks rationale, account scope, and budget cap.", active: "approved", approved: ["proposed", "awaiting_approval", "approved"], action: "increase_budget" },
      { line: 8, label: "Executing", note: "Only now can the harness call the media platform tool.", active: "executing", approved: ["proposed", "awaiting_approval", "approved", "executing"], action: "increase_budget" },
      { line: 9, label: "Executed", note: "The action result is written back to the audit log.", active: "executed", approved: ["proposed", "awaiting_approval", "approved", "executing", "executed"], action: "increase_budget" },
      { line: 2, label: "Rejected path", note: "If policy rejects the scope, the action never reaches execution.", active: "rejected", approved: ["proposed", "rejected"], action: "export_customer_data" },
    ],
  },
  {
    id: "tokenBucket",
    title: "Token Bucket",
    operation: "Control",
    short: "Tool-call rate limiter",
    complexity: "O(1) per request",
    summary:
      "Protect APIs, budgets, and model spend by allowing calls only when the gateway has enough capacity tokens.",
    agentUse:
      "A gateway can stop a reporting agent from hammering Google Ads, DV360, BigQuery, or a commerce API during a retry loop.",
    code: code.tokenBucket,
    steps: [
      { line: 1, label: "Full bucket", note: "The gateway starts with five available tool-call tokens.", tokens: 5, capacity: 5, request: "Google Ads query", allowed: [] },
      { line: 3, label: "Allow first call", note: "The Google Ads query costs one token and is allowed immediately.", tokens: 4, capacity: 5, request: "Google Ads query", allowed: ["Google Ads query"] },
      { line: 3, label: "Burst traffic", note: "Three more campaign metric calls consume most of the remaining capacity.", tokens: 1, capacity: 5, request: "DV360 report", allowed: ["Google Ads query", "Meta query", "DV360 report", "BigQuery lookup"] },
      { line: 5, label: "Throttle", note: "The next request needs two tokens, but only one is available, so the gateway delays it.", tokens: 1, capacity: 5, request: "full account export", allowed: ["Google Ads query", "Meta query", "DV360 report", "BigQuery lookup"], delayed: "full account export" },
      { line: 1, label: "Refill", note: "Time passes and the bucket refills enough to safely run the delayed request.", tokens: 3, capacity: 5, request: "full account export", allowed: ["Google Ads query", "Meta query", "DV360 report", "BigQuery lookup"], delayed: null },
      { line: 4, label: "Allow delayed call", note: "The export now runs without exceeding the API budget.", tokens: 1, capacity: 5, request: "full account export", allowed: ["Google Ads query", "Meta query", "DV360 report", "BigQuery lookup", "full account export"], delayed: null },
    ],
  },
  {
    id: "leaseQueue",
    title: "Lease-Locked Queue",
    operation: "Control",
    short: "Single executor guarantee",
    complexity: "O(log n) claim",
    summary:
      "Let workers claim approved actions with short leases so two agents do not execute the same action at once.",
    agentUse:
      "A runtime can safely run approved campaign actions in the background while recovering from worker crashes and duplicate scheduler ticks.",
    code: code.leaseQueue,
    steps: [
      { line: 1, label: "Approved queue", note: "Three approved actions are ready, but none has a live lock yet.", active: "none", workers: [], actions: [["A1", "approved"], ["A2", "approved"], ["A3", "approved"]] },
      { line: 4, label: "Worker claims A1", note: "Worker A atomically writes a lock token and lease expiry to action A1.", active: "A1", workers: ["worker-a"], actions: [["A1", "locked"], ["A2", "approved"], ["A3", "approved"]] },
      { line: 2, label: "Worker B skips locked A1", note: "A second worker sees the live lease and cannot duplicate the action.", active: "A1", workers: ["worker-a", "worker-b"], actions: [["A1", "locked"], ["A2", "approved"], ["A3", "approved"]] },
      { line: 6, label: "Heartbeat", note: "Worker A refreshes the lease while the media-platform tool call is still running.", active: "A1", workers: ["worker-a"], actions: [["A1", "heartbeat"], ["A2", "approved"], ["A3", "approved"]] },
      { line: 8, label: "Release", note: "The action completes and the lock is released with an executed status.", active: "A1", workers: ["worker-a"], actions: [["A1", "executed"], ["A2", "approved"], ["A3", "approved"]] },
      { line: 5, label: "Expired recovery", note: "If a worker crashes, the expired lease lets another worker reclaim the action later.", active: "A2", workers: ["worker-c"], actions: [["A1", "executed"], ["A2", "locked"], ["A3", "approved"]] },
    ],
  },
  {
    id: "permissionGraph",
    title: "RBAC / ABAC Permission Graph",
    operation: "Control",
    short: "Scope resolver",
    complexity: "O(R + E)",
    summary:
      "Combine roles and attributes to decide whether an agent can touch a specific account, data class, or action.",
    agentUse:
      "A gateway can let a reporting agent read campaign metrics while blocking customer exports or spend changes outside its assigned client scope.",
    code: code.permissionGraph,
    steps: [
      { line: 1, label: "Agent identity", note: "The request starts from a named agent, not a human OAuth token.", active: "agent", allowed: ["agent"], decision: "pending", context: "client=Brand A" },
      { line: 2, label: "Resolve role", note: "The agent maps to the campaign analyst role.", active: "role", allowed: ["agent", "role"], decision: "pending", context: "role=campaign_analyst" },
      { line: 3, label: "Match resource", note: "The request targets a Google Ads account owned by Brand A.", active: "resource", allowed: ["agent", "role", "resource"], decision: "pending", context: "resource=google_ads_brand_a" },
      { line: 4, label: "Check action", note: "Reading metrics is within the role and account scope.", active: "action", allowed: ["agent", "role", "resource", "action"], decision: "allow", context: "action=read_metrics" },
      { line: 4, label: "Attribute block", note: "Exporting customer-level data fails because the data class is restricted.", active: "data", allowed: ["agent", "role", "resource"], blocked: ["data"], decision: "deny", context: "data_class=customer_level" },
      { line: 7, label: "Return decision", note: "The gateway returns allow or deny before any platform tool runs.", active: "decision", allowed: ["agent", "role", "resource", "action", "decision"], blocked: ["data"], decision: "deny", context: "decision recorded" },
    ],
  },
  {
    id: "hashChain",
    title: "Audit Hash Chain",
    operation: "Control",
    short: "Tamper-evident action log",
    complexity: "O(n) verification",
    summary:
      "Link each audit event to the previous event hash so changed or deleted agent actions are detectable.",
    agentUse:
      "A governance layer can prove that campaign actions, approvals, tool calls, and results were not silently edited after execution.",
    code: code.hashChain,
    steps: [
      { line: 1, label: "Genesis", note: "The audit log starts from a known initial hash.", active: 0, events: [["genesis", "0000", "a81c"]], broken: null },
      { line: 2, label: "Approval event", note: "The approval record includes the previous hash before computing its own event hash.", active: 1, events: [["genesis", "0000", "a81c"], ["approved", "a81c", "b42e"]], broken: null },
      { line: 3, label: "Tool call event", note: "The Google Ads tool call links to the approval event hash.", active: 2, events: [["genesis", "0000", "a81c"], ["approved", "a81c", "b42e"], ["tool_call", "b42e", "c90a"]], broken: null },
      { line: 4, label: "Result event", note: "The executed result links to the tool call event.", active: 3, events: [["genesis", "0000", "a81c"], ["approved", "a81c", "b42e"], ["tool_call", "b42e", "c90a"], ["executed", "c90a", "d77f"]], broken: null },
      { line: 5, label: "Replay verification", note: "Verification recomputes the chain and confirms every previous hash matches.", active: 3, events: [["genesis", "0000", "a81c"], ["approved", "a81c", "b42e"], ["tool_call", "b42e", "c90a"], ["executed", "c90a", "d77f"]], broken: null, verified: true },
      { line: 5, label: "Tamper detected", note: "If the tool call event is edited later, the following hash no longer matches.", active: 2, events: [["genesis", "0000", "a81c"], ["approved", "a81c", "b42e"], ["tool_call_edited", "b42e", "9fff"], ["executed", "c90a", "d77f"]], broken: 3, verified: false },
    ],
  },
];

export const algorithms = algorithmItems.map((item) => ({
  ...item,
  context: algorithmContext[item.id],
}));
